language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"

install:
  - npm install -g grunt-cli
  - npm install
  - ./symlink.sh

notifications:
  email: false
